### ISSUE TITLE
Option to turn off fitted plots

### ISSUE THREAD

**Issue by zhexingli** [mzechmeister/GLS#10]
Hello again, is there an option to have the plot only showing the peridogram, ie, leaving out the fitted plots? Thanks.

Zhexing

**Comment by mzechmeister** [comment]
Note the plot is only a working plot and not thought for publication.
Plotting simply the periodogram is also easy via the attributes `f` and `p`
```python
>>> import matplotlib.pyplot as plt
>>> plt.plot(gls.f, gls.p)
>>> plt.show()
```

But I see the need for such an option, since the built-in gls plot has some more enhancements like the period on the top axis, labels, and markers.
So I implemented the plot arguments `gls`, `data`, and `residuals`; all set to `true` by default.
https://github.com/mzechmeister/GLS/blob/73af7bcd6f15858de44c9838b948b5bea22cfb49/python/gls.py#L465
Now, to have only the periodogram, you can now toggle off the other subplots with
```python
>>> gls.plot(data=False, residuals=False)
```

**Comment by zhexingli** [comment]
You're the best :)
