### ISSUE TITLE
FAP level

### ISSUE THREAD

**Issue by zhexingli** [mzechmeister/GLS#9]
Hello,

Is there any way to show a FAP = 1%, 10.% etc or similar overplotted on the periodogram? Thank you.

Best,

Zhexing

**Comment by mzechmeister** [comment]
Thanks for this excellent question and sorry for the late reply. Since the feature could be frequently requested, I have enhanced the code. `plot` returns now the figure object, which can be modified.

So after creating the gls object (here the standard example):
```python
>>> from gls import *
>>> time = np.random.uniform(54000., 56000., 1000)
>>> flux = 0.15 * np.sin(2. * np.pi * time / 10.)
Add some noise
>>> error = 0.5 * np.ones(time.size)
>>> flux += np.random.normal(0, error)
>>> gls = Gls((time, flux, error))
```
one can do now:
```python
>>> fig = gls.plot()
>>> fig.get_axes()[0].axhline(gls.powerLevel(0.01), linewidth=0.5, color='r', dashes=(16, 16))
>>> fig.get_axes()[0].axhline(gls.powerLevel(0.001), linewidth=0.5, color='r', dashes=(16, 8))
```
This produces
![demo_fap_issue_9](https://user-images.githubusercontent.com/32583239/69431364-e2f08f80-0d37-11ea-91f0-05089d2168bc.png)

It might be convenient to have a `FAP` argument in the plot function. However, I guess people want to change at least styles, so that more arguments are required.

**Comment by zhexingli** [comment]
Thank you so much!!!

**Comment by mzechmeister** [comment]
Finally, I implemented in 73af7bc a `fap` plot option.
You can do now:
```python
>>> gls.plot(fap=0.01)
```

**Comment by zhexingli** [comment]
This is awesome, thank you!

**Comment by zhexingli** [comment]
Hello, apologize for bringing this topic back up again. I recently moved to a new device and redownloaded GLS and found errors are returning after running the periodogram. It seems the 'fap' variable within 
`gls.plot(fap=0.01)`
is no longer working? plot funciton doesn't include fap anymore?

I tried to plot fap with another way:
`fig = gls.plot(block=True,period=True)`
`fig.get_axes()[0].axhline(gls.powerLevel(0.01), linewidth=0.5, color='r', dashes=(16, 16))`

But it returns this error:

> AttributeError: module 'matplotlib.pyplot' has no attribute 'get_axes'

which is extremely odd to me.
Any workarounds? Thanks.

**Comment by mzechmeister** [comment]
The FAP level argument is still there:
https://github.com/mzechmeister/GLS/blob/281a964b3f13b0fba1e6f6946ddf8d88e69d9d6c/python/gls.py#L465

Did you follow the install instruction on https://github.com/mzechmeister/GLS/tree/master/python?

Or did you got https://github.com/mzechmeister/python/blob/master/gls.py, which is not synchronised and outdated?

**Comment by zhexingli** [comment]
Oh sorry about that! Yes I got it directly from the github master directory. I'll follow the install instruction. Thanks.
